### ISSUE TITLE
No module named 'pyFaceFrontalization'

### ISSUE THREAD

**Issue by danii92** [hhj1897/face_pose_augmentation#11]
Hi @hhj1897 :

thank you for sharing this project..

kindly i need your help to identify the problem i face when running "python face_pose_augmentation_test.py [-i webcam_index]", 

cause i get error "No module named 'pyFaceFrontalization'"...

1- I notice that you use a .pyx file and import it right away without compilation (from .pyx to .pyd) ..

2- I try to compile "pyFaceFrontalization.pyx" to ".pyd" to import it as usual , but compilation failed with some errors..

your feedback is highly appreciated..thanks

**Comment by hhj1897** [comment]
We use Cython to handle the compilation of the C++ code. Compilation is done by the setup script (when you run "pip install -e ."). For this to work, you will usually need to have GCC + CMake (Linux) or Visual Studio Build Tools (Windows) installed on your machine.

**Comment by danii92** [comment]
Hi @hhj1897 :

thank you for your support , the problem solved after running "pip install -e ."

can i run the all (p, y, r) with related value as one process on a folder of images ?

thanks again

**Comment by hhj1897** [comment]
Yes, you can change yaw, pitch, and roll in one go. But this is not advised. This seem my reply in #14 .
