### ISSUE TITLE
Reduce Stretching Effect on Face Border

### ISSUE THREAD

**Issue by Mayur28** [hhj1897/face_pose_augmentation#12]
Hi!

Thanks for publicly releasing this amazing solution!

I've just been experimenting with the solution, and I noticed that as the pose angle (specifically, along the yaw axis), the there is a stretching effect along the face.
To illustrate what I mean, I have attached the result of a talking face video that I want to rotate, and the second video is the result produced after performing face detection and extracting the face crop.

If anyone has any advice on minimizing this minimizing/ disappearing effect along the face contour, it would be highly appreciated.
Thanks!

https://user-images.githubusercontent.com/26574827/198726123-22b49e61-890d-4969-afad-9c4cfc6fb496.mp4

https://user-images.githubusercontent.com/26574827/198726135-ef9fff25-a116-49ac-9071-5741aedb3145.mp4

**Comment by Mayur28** [comment]
If anyone is unable to view the videos, please refer to the image below.
![image](https://user-images.githubusercontent.com/26574827/198726626-11a42be1-a953-41ed-a074-24accb7dc56e.png)

**Comment by jacksoncsy** [comment]
Hey Mayur, 

Sorry that I just saw this issue. I hope my email answered your questions well. If yes, we can close this issue.

Thanks,
Shiyang

**Comment by rlczddl** [comment]
I also want to ask the same question, can you post the answer here?

**Comment by Mayur28** [comment]
The reason for missing texture is because 3DDFA fails to fit the face boundary very accurately, this is a known issue. Due to this, the background textures will be stretched when rotating the face.

This often happens in frontal face and cannot be solved easily. In practice, the idea is to just augment those slightly non-frontal face to a larger degree (in the same yaw/pitch direction), which will produce less artifacts.

**Comment by rlczddl** [comment]
Thanks for the replies and suggestions. In fact I just did what you suggested.

**Comment by Mayur28** [comment]
Great! Did you manage to resolve the issue (the stretching effect)? Did you swap out any of the components such as the landmark detector?

**Comment by rlczddl** [comment]
I didn't swap the components, I just used the face at the corresponding angle to further increase the angle to generate the result, which is better than using only the frontal face.The result is as follows:
![image](https://user-images.githubusercontent.com/21055131/201309788-ce85b0c0-4124-4b1d-bb02-54cf210aa182.png)

**Comment by Mayur28** [comment]
Understood, thank you.
