### ISSUE TITLE
How to run on a single image

### ISSUE THREAD

**Issue by cleardusk** [hhj1897/face_pose_augmentation#2]
1. Clone three repos: face_detection, face_alignment and face_pose_augmentation, and pip install them successfully.
2. Refer to these lines of code: https://github.com/hhj1897/face_pose_augmentation/blob/6504c70c8d7784b20e3bf044ccf0a90dd238c434/face_pose_augmentation_test.py#L165-L187
3. Call `augmentation_results = augmentor(image, tddfa_result, delta_poses, landmarks)`, and parse the `augmentation_results` variable to get the profiled image, landmark, and correspondence.

**Comment by jacksoncsy** [comment]
Hello @cleardusk, thanks for the comments! Another way to run single/multiple images is to use: [face_pose_augmentation_main.py](https://github.com/hhj1897/face_pose_augmentation/blob/b5c90f2d381986ab7c87cfc111ca35badfebd20c/face_pose_augmentation_main.py#L55)
