### ISSUE TITLE
Euler angles for yzx rotation

### ISSUE THREAD

**Issue by georgeYanch** [hhj1897/face_pose_augmentation#5]
Hi, could you please explain how to modify get_euler_angles function when dealing with pitch-yaw-roll rotation matrix?

Thanks in advance!

**Comment by jimmysue** [comment]
> Hi, could you please explain how to modify get_euler_angles function when dealing with pitch-yaw-roll rotation matrix?
> 
> Thanks in advance!

You could refer this to  http://eecs.qmul.ac.uk/~gslabaugh/publications/euler.pdf

**Comment by jacksoncsy** [comment]
The question has been answered, thanks @jimmysue
