### ISSUE TITLE
Angles don't correspond to rotation matrices

### ISSUE THREAD

**Issue by georgeYanch** [hhj1897/face_pose_augmentation#6]
Hi, in utils.py `make_rotation_matrix` method you construct rotation matrices in such a way:

rot_x for pitch (but x rotation is roll)
rot_y for yaw (but it's pitch)
rot_z for roll (but it's yaw)

Why is your rotation convention differs so much?

**Comment by jacksoncsy** [comment]
It seems that Jie has explained this quite well, I am closing this issue.
